version: "3.8"

services:
  web:
    build: .
    container_name: myapp_web
    privileged: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: myapp_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ncst
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myapp_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpass
    privileged: true
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
