services:
  web:
    build: .
    container_name: myphp_web
    privileged: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - uploads:/var/www/html/assets/userProfile
    depends_on:
      - db
    # Add this to ensure proper user permissions
    user: "www-data:www-data"

  db:
    image: mysql:8
    container_name: myapp_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ncst
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpass
    privileged: true
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
  uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/uploads